### PR TITLE
Feature/bitly links

### PR DESCRIPTION
**Pull request by RegularSvensson**
MainActivity.java changed.

### CODE REVIEW

**Comment by dgenelov** [comment]
Please declare the date-text as a global variable instead of calling the findViewById-method twice

**Comment by sarakinell** [comment]
**Thoughts:**

I like the added text to make sure the email receiver clicks the link, @RegularSvensson! Well done with adding date to the subject as ”Your ElectriCity report for [date]”! 

**To be changed:**
- [x] Add complete javadoc for the class description of DatePickerFragment.
- [x] There are three extra spaces on line 84 in MainActivity (after EXTRA_TEXT)
- [ ] Maybe we should swap the order of the date properties to make it more intuitive for our Swedish users? E.g. use 2016-05-20 instead of 20-5-2016.

**Comment by melindaflp** [comment]
We are not changing the last task because an other group is working on it.

**Comment by melindaflp** [comment]
We chose not to coment on the override, since it has the same usage as the inheritage.

**Comment by RegularSvensson** [comment]
- [x] We will also update the bitly links

**Pull request merged**
