### PR TITLE
Limit datepicker to 19-25th may for final presentation

### PR DESCRIPTION
**Pull request by dgenelov**
DateDialog.java changed

### CODE REVIEW

**Comment by sarakinell** [comment]
**Thoughts:**

Well done with restricting the user from choosing an ”invalid” date in the DatePicker, @dgenelov & @RegularSvensson! Brilliant! An even better solution might be to create a method that calculates the dates for a week back and today’s date, and then sets minDate and maxDate accordingly. Maybe it could return a field of Strings for the different dates and be used in the switch statements in MainActivity as well?

”Report missing for chosen date” is shown when there is no date chosen. Shouldn’t the default message be updated? Or even better - maybe the user should not be able to press the send button if no date has been picked?

**To be changed:**
- [x] We do not want the user to be able to generate a report for the 25th of May. We will present in the afternoon and all information generated in the report will not be accurate if the 25th is chosen. Being able to choose 18th-24th would be a better solution.
- [x] Is the dialog object created for last year (2015) on line 48?
- [x] It looks like minDate and maxDate is set for April, is number 4 as second argument correct?
- [x] Comments in MainActivity need to be uniform, use DateDialog or datedialog or dateDialog, not all three. Be persistent throughout the code. In the DateDialog class, both ”DatePicker” and ”date picker” has been used.
- [x] In DateDialog, the content of the constructor taking a View as argument should be written one line below the method declaration. Let the last curly bracket be another line below the setting of textToChange.
- [x] The javadoc for onCreateDialog has a spelling error. ”todays” should be ”today’s”.
- [x] In the comments for onCreateDialog, on line 52 and 53, it should be written ”May”, not ”may”. 
- [x] ”show” on line 69 should be written with capital S.

**Comment by dgenelov** [comment]
Thank you @sarakinell for your most valuable input!
I tried to correct everything according to your wishes. I will address your comments one by one below:
1. It's true that we should not be able to generate a report for the 25th. The reason it's 19th to 25th in the app is because those where the dates that we had .csv-files available for in Firebase storage. We should probably change it to 18th-24th, but that will require also changing one of the .csv-files. We can talk about that tomorrow.
2. That's correct. Thanks!
3. For some reason, The calendars' month variable starts out at 0 with January, and therefore May is #4. It is quite peculiar, as the date variable starts out at 1. 
4. Thanks! I changed it all to DateDialog (which is the class name) now.
5. Thanks, I think I understood what you meant. Check it out to see if it's right now.
6. Thanks! I changed, but to todays' instead of today's, as I think that is even more correct(?).
7. Thanks! Changed it. 
8. Thanks again, got it :)

And for your general comments: 
- We chose not to let the method count back one week from todays date, as that would not be consistent with the other coding we have done for this release. If the .csv-files on Firebase Storage is restricted to seven days, it should be those seven days that is possible to choose from with the datepicker. Do you agree?
- I do believe we fixed this in another branch. If the user has not chosen a date and still pushes the send-button, a Toast pops up asking the user to select a date.

Again, thank you for your very good feedback Sara!

**Comment by sarakinell** [comment]
Thanks for your quick reply @dgenelov! Please commit your changes for me to verify.

**Comment by dgenelov** [comment]
I committed 9 minutes ago, but for some reason it seems like I managed to make the commit on a new branch(!) called "oneWeekDatePickers", not "oneWeekDatepickers". I'll delete that branch and redo the changes in the original one to clean up this mess.

**Comment by dgenelov** [comment]
Now the commit should be up and running

**Comment by sarakinell** [comment]
1. I understand. Looking forward to discussing it further tomorrow!
2. Thank you for the explanation! 
3. Both DatePicker (line 10) and datepicker (line 52) are still used. Maybe not part of this pull request though, but still needs to be fixed?
4. Looks flawless.
5. Nope, should be "today's date", not "todays' date", I'm afraid :) The car's tyres = one car, the cars' tyres = several cars. Just this one small fix until I'll merge, promise!

**Answers to (answers to) comments:**
- Completely understand if it is not considered within the scope of this release. I do agree that you should choose dates corresponding to files in Firebase! Let's discuss possible solutions tomorrow during sprint planning.
- Yep, all good.

Well done @dgenelov!

**Comment by dgenelov** [comment]
New update, tried to fulfill your wishes.

**Pull request merged**
